config/routes.rb
Rails.application.routes.draw do
  devise_for :users, controllers: { registrations: "registrations" }

  authenticated do
    root :to => 'applications#index', as: :authenticated
  end

  root :to => 'home#index'

  resources :home, only: [:index]
  resources :applications do
    resources :probes do
      resources :reports, only: [:index]
    end
    resources :reports, only: [:index]
  end
  resources :reports, only: [:index, :show]
  resource :user_accounts, only: [:show]
  namespace :api do
    resources :probe_infos
  end
end

app/models/application.rb
class Application < ActiveRecord::Base
  belongs_to :user
  has_many :probes
  has_many_documents :results

  def update_characteristics
    qual_statuses = {
      bad: 0.0,
      ok: 0.5,
      good: 1.0
    }

    qual_percentage = {}
    probes.each do |p|
      if p.quality_characteristics
        probe_chars = {}
        p.quality_characteristics.each do |q|
          result = p.results.last
          if qual_percentage[q]
            qual_percentage[q] << (result.nil? ? :bad : result.status)
          else
            qual_percentage[q] = [result.nil? ? :bad : result.status]
          end
          probe_chars[q] = [result.nil? ? :bad : result.status]
        end
        p.update_attributes(Hash[probe_chars.map { |k,v| [ k, v.inject(0) { |sum,status| sum + qual_statuses[status] }/v.count.to_f ] }])
      end
    end

    update_attributes(Hash[qual_percentage.map { |k,v| [ k, v.inject(0) { |sum,status| sum + qual_statuses[status] }/v.count.to_f ] }])
  end

  def results_danger?
    results.select { |r| r.status == :bad }.count > 0
  end
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  before_action :authenticate_user!
  protect_from_forgery with: :exception
end

app/controllers/applications_controller.rb
class ApplicationsController < ApplicationController
  def index
    @applications = current_user.applications
  end

  def new
    @app = Application.new
  end

  def create
    @app = Application.new
    @app.name = params[:application][:name]
    @app.user = current_user

    @app.save!

    redirect_to applications_path
  end

  def destroy
    @app = Application.find(params[:id])
    @app.destroy if @app.user_id == current_user.id

    redirect_to applications_path
  end

  def edit
    @app = Application.find(params[:id])

    raise ActionController::RoutingError.new('Not Found') unless @app.user_id == current_user.id
    render 'new'
  end

  def update
    @app = Application.find(params[:id])
    @app.name = params[:application][:name]
    @app.save! if @app.user_id == current_user.id

    raise ActionController::RoutingError.new('Not Found') unless @app.user_id == current_user.id

    redirect_to applications_path(@app)
  end

  private
  def person_params
    params.require(:application).permit(:name)
  end
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/applications_helper.rb
module ApplicationsHelper
end

app/views/applications/index.html.haml
%a.ui.button{ href: new_application_path } Create application

%table.ui.celled.table
  %thead
    %tr
      %th ID
      %th Name
      %th.collapsing
  %tbody
    - @applications.each do |app|
      %tr
        %td= app.id
        %td.name{ onclick: "document.location = '#{application_probes_path(app)}'" }
          = app.name
        %td.actions
          = link_to application_reports_path(app), class: "ui icon button" do
            %i.tasks.icon
          = link_to edit_application_path(app), class: 'ui icon button' do
            %i.write.icon
          = link_to application_path(app), method: :delete, class: 'ui icon button' do
            %i.remove.icon

app/views/applications/new.html.haml
= form_for @app, html: { class: 'ui form' } do |f|
  %form.ui.form
    .field
      .label Application name
      = f.text_field :name
    = f.submit