config/routes.rb
Rails.application.routes.draw do
  devise_for :users, controllers: { registrations: "registrations" }

  authenticated do
    root :to => 'applications#index', as: :authenticated
  end

  root :to => 'home#index'

  resources :home, only: [:index]
  resources :applications do
    resources :probes do
      resources :reports, only: [:index]
    end
    resources :reports, only: [:index]
  end
  resources :reports, only: [:index, :show]
  resource :user_accounts, only: [:show]
  namespace :api do
    resources :probe_infos
  end
end

app/models/probe.rb
class Probe < ActiveRecord::Base
  belongs_to :application
  has_many :probe_infos
  has_many_documents :results

  serialize :quality_characteristics, JSON

  # after_update :recalculate_probe_infos

  def recalculate_probe_infos
    probe_infos.each do |probe_info|
      ProbesWorker.perform_async(probe_info.id)
    end
  end

  def results_danger?
    results.select { |r| r.status == :bad }.count > 0
  end
end

app/controllers/probes_controller.rb
class ProbesController < ApplicationController
  def index
    @app = Application.find(params[:application_id])

    raise ActionController::RoutingError.new('Not Found') unless @app.user_id == current_user.id
  end

  def new
    @app = Application.find(params[:application_id])
    @probe = Probe.new

    raise ActionController::RoutingError.new('Not Found') unless @app.user_id == current_user.id
  end

  def edit
    @app = Application.find(params[:application_id])
    @probe = Probe.find(params[:id])

    raise ActionController::RoutingError.new('Not Found') unless @app.user_id == current_user.id

    render 'new'
  end

  def create
    @app = Application.find(params[:application_id])

    raise ActionController::RoutingError.new('Not Found') unless @app.user_id == current_user.id

    @probe = Probe.new
    @probe.application_id = @app.id
    @probe.name = params[:probe][:name]
    @probe.script = params[:probe][:script]
    @probe.analyzer = params[:analyzer]
    @probe.quality_characteristics = params[:quals].split(',')
    @probe.save!

    redirect_to application_probes_path(@app)
  end

  def update
    @app = Application.find(params[:application_id])

    raise ActionController::RoutingError.new('Not Found') unless @app.user_id == current_user.id

    @probe = Probe.find(params[:id])
    @probe.application_id = @app.id
    @probe.name = params[:probe][:name]
    @probe.script = params[:probe][:script]
    @probe.analyzer = params[:analyzer]
    @probe.quality_characteristics = params[:quals].split(',')
    @probe.save!

    redirect_to application_probes_path(@app)
  end

  def destroy
    @app = Application.find(params[:application_id])
    
    raise ActionController::RoutingError.new('Not Found') unless @app.user_id == current_user.id

    @probe = Probe.find(params[:id])
    @probe.destroy

    redirect_to application_probes_path(@app)
  end
end

app/helpers/probes_helper.rb
module ProbesHelper
end

app/views/probes/index.html.haml
%a.ui.button{ href: new_application_probe_path(@app) } Create probe

#container
:javascript
  var xs = ['suitability', 'performance', 'compatibility', 'usability', 'reliability', 'security', 'maintainability', 'portability'];
  Highcharts.chart('container', {
    chart: { polar: true },
    title: { text: 'Application health' },
    pane: { startAngle: 0, endAngle: 360 },
    xAxis: {
        tickInterval: 45,
        min: 0,
        max: 360,
        labels: {
            formatter: function () {
                return xs[this.value/45];
            }
        }
    },
    yAxis: { min: 0, max: 1 },
    plotOptions: {
        series: {
            pointStart: 0,
            pointInterval: 45
        },
        column: {
            pointPadding: 0,
            groupPadding: 0
        }
    },

    series: #{JSON.dump [{name: 'Application', data: @app.attributes.slice('suitability', 'performance', 'compatibility', 'usability', 'reliability', 'security', 'maintainability', 'portability').values}] + @app.probes.map{ |p| { type: 'area', name: p.name, data: p.attributes.slice('suitability', 'performance', 'compatibility', 'usability', 'reliability', 'security', 'maintainability', 'portability').values} }}
  });

%table.ui.celled.table
  %thead
    %tr
      %th ID
      %th Name
      %th Quality characteristics
      %th.collapsing
  %tbody
    - @app.probes.each do |probe|
      %tr
        %td= probe.id
        %td= probe.name
        %td
          - probe.quality_characteristics.each do |qual|
            .ui.button.disabled
              = qual
        %td.actions
          = link_to application_probe_reports_path(@app, probe), class: "ui icon button" do
            %i.tasks.icon
          = link_to edit_application_probe_path(@app, probe.id), class: 'ui icon button' do
            %i.write.icon
          = link_to application_probe_path(@app, probe), method: :delete, class: 'ui icon button' do
            %i.remove.icon

app/views/probes/new.html.haml
= form_for [@app, @probe], html: { class: 'ui form' } do |f|
  %form.ui.form
    .field
      .label Probe name
      = f.text_field :name
    .field
      .label Quality characteristics
      .ui.fluid.multiple.search.selection.dropdown
        %input{type: :hidden, name: 'quals', value: (@probe.quality_characteristics || []).join(',')}
        %i.dropdown.icon
        %input.search{autocomplete: 'off', tabindex: 0}
        %span.sizer
        .default.text Quality characteristics
        .menu.transition
          - [:suitability, :performance, :compatibility, :usability, :reliability, :security, :maintainability, :portability].each do |char|
            .item{'data-value' => char, 'data-text' => char.capitalize}
              #{char.capitalize}
    .field
      .label Analyzers
      .ui.fluid.search.selection.dropdown
        %input{type: :hidden, name: 'analyzer', value: @probe.analyzer}
        %i.dropdown.icon
        %input.search{autocomplete: 'off', tabindex: 0}
        %span.sizer
        .default.text Analyzer
        .menu.transition
          - Analyzers.constants.select { |c| Analyzers.const_get(c).is_a?(Class) && c.to_s.end_with?('Analyzer') }.each do |char|
            .item{'data-value' => char, 'data-text' => char}
              #{char}
    .field.script
      .label Probe script
      #probe_mock_script
      = f.hidden_field :script
    = f.submit
:javascript
  var editor = ace.edit('probe_mock_script');
  var javaScriptMode = ace.require('ace/mode/javascript').Mode;

  editor.setTheme("ace/theme/twilight");
  editor.session.setMode(new javaScriptMode());

  $('.ui.form').submit(function() {
    $('#probe_script').val(editor.getSession().getValue());
  });