config/routes.rb
Rails.application.routes.draw do
  devise_for :users, controllers: { registrations: "registrations" }

  authenticated do
    root :to => 'applications#index', as: :authenticated
  end

  root :to => 'home#index'

  resources :home, only: [:index]
  resources :applications do
    resources :probes do
      resources :reports, only: [:index]
    end
    resources :reports, only: [:index]
  end
  resources :reports, only: [:index, :show]
  resource :user_accounts, only: [:show]
  namespace :api do
    resources :probe_infos
  end
end

app/controllers/reports_controller.rb
class ReportsController < ApplicationController
  def index
    @page = params[:page] || 1

    if params[:probe_id]
      app = Probe.find(params[:probe_id]).application

      raise ActionController::RoutingError.new('Not Found') unless app.user_id == current_user.id

      results = Probe.find(params[:probe_id]).results.order_by(created_at: :desc).page(@page)
    elsif params[:application_id]
      app = Application.find(params[:application_id])

      raise ActionController::RoutingError.new('Not Found') unless app.user_id == current_user.id

      results = Application.find(params[:application_id]).results.order_by(created_at: :desc).page(@page)
    else
      results = Result.where(:application_id.in => current_user.applications.pluck(:id)).order_by(created_at: :desc).page(@page)
    end

    @reports = results
  end

  def show
    @report = Result.find(params[:id])
    @app = @report.application

    raise ActionController::RoutingError.new('Not Found') unless @app.user_id == current_user.id
  end
end

app/views/reports/index.html.haml
%table.ui.celled.table
  %thead
    %tr
      %th Status
      %th Probe
      %th Datetime
  %tbody
    - @reports.each do |report|
      %tr{ onclick: "document.location = '#{report_path(report)}'" }
        %td= report.status
        %td= report.probe.name
        %td= report.created_at.strftime('%d.%m.%Y %H:%M')
  = paginate @reports

app/views/reports/show.html.haml
%h1
  Report for application #{@app.name} (#{@report.probe.name}) from #{@report.created_at.strftime('%d.%m.%H')}

= line_chart(@report.series.map { |k,v| { name: k, data: v }}, min: nil, max: nil, adapter: 'highcharts')

%h2 Problematic modules
%table.ui.celled.table
  %thead
    %tr
      %th File
      %th Score
  %tbody
    - @report.problematic_modules.each do |mod|
      %tr
        %td= mod["name"]
        %td= mod["maintainability"]